-- name: migrate

CREATE TABLE public.short_link
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 99999999 CACHE 1 ),
    title character varying(128) COLLATE pg_catalog."default" NOT NULL,
    url character varying(2048) COLLATE pg_catalog."default" NOT NULL,
    hash_str character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT short_link_pkey PRIMARY KEY (id),
    CONSTRAINT hash_uk UNIQUE (hash_str)
)
